name: clicli_dark
description: CliCli Dark. clicli 纯黑.

version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  fluttertoast: any
  flutter_svg: any
  dio: any
  cached_network_image: any
  video_player: any
  wakelock: any
  screen: any
  open_iconic_flutter: any
  # super_rich_text: any
  flutter_markdown: ^0.3.3
  url_launcher: any

flutter:
  uses-material-design: true
  assets:
    - assets/
